### ISSUE TITLE
Edges z-index?

### ISSUE THREAD

**Issue by scramatte** [txlabs/vnodes#22]
Hi,

How can I change edges z-index?

Regards

**Comment by tiagolr** [comment]
a global style setting .edge z-index should do, eg:

```css
.edge {
  z-index: 1000
}
```
